# Generated by Django 4.1 on 2022-08-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'SMS Token',
                'verbose_name_plural': 'SMS Tokens',
                'ordering': ['-id'],
            },
        ),
    ]
