# Generated by Django 4.1 on 2022-08-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_smslog_smstoken_create_at_smstoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstoken',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
