# Generated by Django 4.1 on 2022-08-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_alter_smstoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstoken',
            name='token',
            field=models.TextField(),
        ),
    ]
